openapi: 3.2.0
info:
  title: OpenAPI definition System Rest API
  version: v0
servers:
- url: https://api.sp4eu.uw.edu.pl
tags:
- name: system-rest
paths:
  /system/git:
    get:
      tags:
      - system-rest
      operationId: gitProperties
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/GitProperties'
      summary: Git properties
      x-summary-source: derived
  /system/build:
    get:
      tags:
      - system-rest
      operationId: buildProperties
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/BuildProperties'
      summary: Build properties
      x-summary-source: derived
components:
  schemas:
    BuildProperties:
      type: object
      properties:
        name:
          type: string
        time:
          type: string
          format: date-time
        version:
          type: string
        group:
          type: string
        artifact:
          type: string
    GitProperties:
      type: object
      properties:
        branch:
          type: string
        shortCommitId:
          type: string
        commitTime:
          type: string
          format: date-time
        commitId:
          type: string
  securitySchemes:
    Authorization:
      type: apiKey
      name: Authorization
      in: header
